# Read the Docs configuration file for Sphinx projects
# Required

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
      install:
        - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
